# Generated by Django 2.0.1 on 2018-03-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
